### ISSUE TITLE
Galaxy Site Down?

### ISSUE THREAD

**Issue by marencc** [QBRC/PIPE-CLIP#3]
Hi! 

I was wondering, It's been a week or so since the Galaxy Site can’t be reached, is this going to be permanent? We've used your pipeline for some of your analysis and we will be publishing soon. But we can't access and update the results!

Thank you very much,

**Comment by bchen4** [comment]
@marencc Site is up. Thank you very much.

**Comment by marencc** [comment]
Hello!

The server is down again!!

Many thanks!!
